<!DOCTYPE html>
<html>
<head>
	<title>This is a upload test</title>
</head>
<body>
<h5>上传视频测试</h5>
<div id="uploadbox">
	<form id="upload" action="/video" enctype="multipart/form-data" method="POST">

		<?php foreach ($params as $label => $value): ?>
		<p>
			<label for=""><?=$label?></label>
			<?php if ($label == 'target'): ?>
			<textarea name="target" style="width:800px;height:100px"><?=$value?></textarea>
			<?php else:?>
			<input type="text" name="<?=$label?>" value='<?=$value?>'>
			<?php endif;?>
		</p>
		<?php endforeach; ?>

		<!-- 表单提交的情况下，可使用POST加_method参数模拟PUT、DELETE请求 -->
		<input type="hidden" name="_method" value="put" />

		<p><input type="file" name="files[]"></p>
		
		<button type="submit">上传</button>
	</form>
</div>
</body>
</html>